### ISSUE TITLE
Replace Canvas with UI Toolkit 

### ISSUE THREAD

**Issue by tacman** [MinaPecheux/Unity-IcoPop#1]
First, thanks for releasing a Unity VR game that works and is complicated enough to be interesting, and not so complicated that it's hard to understand.  

This seems to be a good candidate for using the new UI Toolkit.  It's possibly something I can do, I've been playing around with it, and I finally feel like Unity has professional UI tools (css and xml!)

Also, can you add a README with a link back to the article at https://blog.codemagic.io/building-and-publishing-a-vr-unity-game-for-oculus-with-codemagic/, and also a license?

Again, kudos on the release.

**Comment by MinaPecheux** [comment]
Heya!
Thanks a lot for your nice comment - I'm really happy you like the repo and you think it's interesting :)
Also, you're totally right about the readme/license, I got caught up in other things and forgot to add them; that's now fixed!

About the UI Toolkit: I would rather not switch for this specific repo: since this repo is used as the "sample project" for the Codemagic article, I would prefer it stayed pretty "basic" and used built-in tools as much as possible when it's not related to VR.

BUT! I would be super glad if you'd forked the project and made your own version using the UI Toolkit, and I would of course relink to it (here in my readme) when it's done if you want :D

Hope you understand,
cheers! :)

(I'm closing this issue but feel free to re-open another specifically on this topic if you want of course!)
